
name: CI

on: [pull_request, push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/kibana-oss
          ref: 7.6.1
          token: ${{secrets.OD_ACCESS}}
          path: kibana
      - name: Checkout Plugin
        uses: actions/checkout@v1
        with:
          path: kibana/plugins/sql-kibana-plugin
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.19.0'
      - name: Kibana Pluign Bootstrap
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: yarn kbn bootstrap
      - name: Build Artifact
        run: |
          yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: sql-kibana.zip
          path: ./build/*.zip
